import { createFileRoute } from "@tanstack/react-router";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PageIntro, SectionCTA, meta } from "@/components/site";
export const Route = createFileRoute("/faq")({ head: () => meta("Preguntas frecuentes", "Resolvemos tus dudas sobre presupuestos, coberturas, cambios de compañía y siniestros en GS Ansalong, Bellpuig."), component: Faq });
const questions = [
  ["¿Tengo que vivir cerca de vuestra oficina o ir hasta allí para contratar?", "No. Atendemos a clientes de toda la provincia de Lleida y, en muchos casos, el estudio, el presupuesto y buena parte de los trámites se pueden hacer por teléfono, email o videollamada por Teams. Si prefieres hablar en persona, puedes venir a nuestra oficina."],
  ["¿Trabajáis con una sola aseguradora?", "No. Trabajamos con Zurich, ARAG y DKV, y te proponemos la que mejor encaja con lo que necesitas en cada caso."],
  ["¿Atendéis a autónomos y empresas?", "Sí. Tenemos seguros pensados para autónomos, comercios y pymes, desde la responsabilidad civil hasta la ciberprotección, y opciones de salud para ti y para tu equipo."],
  ["¿Pedir un presupuesto me compromete a algo?", "No. Estudiar tu caso y prepararte un presupuesto es sin compromiso."],
  ["¿Qué datos necesito para pedir un presupuesto?", "Depende del seguro. Para el coche suele bastar con la matrícula, tu DNI y la fecha de tu carné de conducir. Para el hogar, la dirección de la vivienda, sus metros y el año de construcción. Para vida o salud, algunos datos personales. En cada caso te decimos exactamente qué necesitamos."],
  ["¿Puedo cambiar de compañía si ya tengo un seguro?", "Sí. Revisamos tu póliza actual y te decimos si hay una opción mejor, sin compromiso. Si decides cambiar, conviene no dar de baja la póliza actual hasta tener la nueva en vigor, para no quedarte sin cobertura. Y ten en cuenta que, normalmente, si no quieres renovar hay que avisar a la compañía con un mes de antelación."],
  ["¿Qué diferencia hay entre un seguro a terceros y uno a todo riesgo?", "El seguro a terceros cubre los daños que causes a otras personas o vehículos. El todo riesgo cubre además los daños de tu propio coche, con o sin franquicia. En medio están los terceros ampliados, que suman coberturas como lunas, robo o incendio. La opción adecuada depende del valor del coche y de cuánto lo uses."],
  ["¿Cuánto capital tengo que asegurar en un seguro de vida?", "No hay una cifra que valga para todos. Depende de las deudas que tengas, de cuántas personas dependen de tus ingresos y durante cuánto tiempo. Lo calculamos contigo a partir de tu situación."],
  ["¿Qué cubre la protección jurídica?", "Cuando surge un conflicto, el seguro se hace cargo de los gastos de tu defensa (abogado, procurador y otros trámites) hasta el límite contratado, y puedes consultar dudas legales. Antes de contratar conviene revisar qué materias incluye la póliza, porque no todas cubren lo mismo."],
  ["¿Qué hago si tengo un siniestro?", "Si hay heridos o peligro, llama primero al 112. Después avísanos cuanto antes, por teléfono, por email o en la oficina, porque las pólizas fijan plazos para comunicar un siniestro. Reúne fotos y los datos de las personas implicadas, y nosotros te indicamos cómo seguir y nos ocupamos del seguimiento hasta que se resuelva."],
];
function Faq() { return <><PageIntro eyebrow="RESOLVEMOS TUS DUDAS" title="Preguntas frecuentes."><p>Respuestas claras a las dudas que suelen surgir antes y después de contratar un seguro.</p></PageIntro><section className="section site-container"><Accordion type="single" collapsible className="faq-wrap">{questions.map(([question,answer],i) => <AccordionItem className="faq-item" value={`q-${i}`} key={question}><AccordionTrigger className="faq-trigger">{question}</AccordionTrigger><AccordionContent className="faq-content">{answer}</AccordionContent></AccordionItem>)}</Accordion></section><SectionCTA title="¿Te queda alguna pregunta?" text="Estaremos encantados de escucharla y ayudarte a encontrar la respuesta." label="Contacta con nosotros" asunto="contacto"/></>; }