import { createFileRoute } from "@tanstack/react-router";
import { CarFront, House, HeartPulse, Scale, ShieldPlus, BriefcaseBusiness } from "lucide-react";
import { PageIntro, SectionCTA, meta } from "@/components/site";
export const Route = createFileRoute("/seguros")({ head: () => meta("Seguros", "Seguros para autónomos, empresas, coche, hogar, vida, protección jurídica y salud en todo el territorio nacional. Coberturas adaptadas a tu situación."), component: Insurance });
const items = [
  { icon: BriefcaseBusiness, title: "Autónomos y empresas", content: <><p>Si tienes un comercio, un taller, una oficina o cualquier otro negocio, el seguro tiene que proteger dos cosas: lo que tienes y lo que podrías llegar a pagar. Trabajamos cuatro líneas:</p><ul><li><b>Responsabilidad civil:</b> los daños que tu actividad pueda causar a terceros.</li><li><b>Multirriesgo de negocio:</b> local, instalaciones y existencias frente a incendio, robo, agua y otros daños.</li><li><b>Ciberprotección:</b> ataques informáticos, bloqueo de sistemas y fuga de datos.</li><li><b>Accidentes:</b> cobertura para ti y para tu equipo.</li></ul><p>Al estudiar tu caso también tenemos en cuenta qué pasaría con tus ingresos si tuvieras que parar la actividad unos meses.</p></> },
  { icon: CarFront, title: "Coche", content: <p>Desde el seguro a terceros hasta el todo riesgo, con opciones intermedias. La elección depende del uso que le des al coche, de su edad y de lo que costaría repararlo o sustituirlo, y te la planteamos con esos datos. A veces lo más sensato es la opción más económica.</p> },
  { icon: House, title: "Hogar", content: <p>Protege tu vivienda habitual, tu segunda residencia o un piso de alquiler, seas propietario o inquilino. Según la póliza, cubre los daños por incendio, robo o agua, la responsabilidad civil si un desperfecto en tu casa afecta al vecino y un servicio de asistencia para las urgencias.</p> },
  { icon: HeartPulse, title: "Vida", content: <p>Está pensado para que, si te ocurre algo grave, tu familia no tenga además un problema económico: la hipoteca, los estudios de los hijos, el día a día. Ajustamos el capital y las coberturas a tu situación familiar y laboral, y las revisamos cuando esa situación cambia: la compra de una vivienda, un hijo, un negocio propio.</p> },
  { icon: Scale, title: "Protección jurídica · ARAG", content: <p>Defensa y asesoramiento legal para los conflictos del día a día: una reclamación de consumo, un problema con la vivienda, un accidente de circulación o un conflicto laboral. El seguro se hace cargo de los gastos de defensa hasta el límite que hayas contratado.</p> },
  { icon: ShieldPlus, title: "Salud y dental · DKV", content: <p>Un cuadro médico privado para consultas, pruebas y especialistas, con coberturas dentales. Hay opciones para particulares y familias, para autónomos y para empresas, por ejemplo como beneficio para la plantilla. Pensado para quien prefiere elegir médico y agilizar consultas y pruebas.</p> },
];
function Insurance() { return <><PageIntro eyebrow="QUÉ PROTEGEMOS" title="Seguros pensados para tu vida."><p>Estos son los seguros que gestionamos. Las coberturas exactas y el precio dependen de cada caso, por eso cada propuesta empieza con una conversación. Lo que ves aquí es lo que suelen cubrir.</p></PageIntro><section className="section site-container"><div className="detail-list">{items.map(({ icon:Icon,title,content }) => <article className="detail-card" key={title}><Icon/><h2>{title}</h2>{content}</article>)}</div></section><SectionCTA/></>; }