/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ComoTrabajamosRouteImport } from './routes/como-trabajamos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as QuienTeAtiendeRouteImport } from './routes/quien-te-atiende'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as SegurosRouteImport } from './routes/seguros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabajamosRoute = ComoTrabajamosRouteImport.update({
  id: '/como-trabajamos',
  path: '/como-trabajamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienTeAtiendeRoute = QuienTeAtiendeRouteImport.update({
  id: '/quien-te-atiende',
  path: '/quien-te-atiende',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/quien-te-atiende': typeof QuienTeAtiendeRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/seguros': typeof SegurosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/quien-te-atiende': typeof QuienTeAtiendeRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/seguros': typeof SegurosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/quien-te-atiende': typeof QuienTeAtiendeRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/seguros': typeof SegurosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/como-trabajamos'
    | '/contacto'
    | '/faq'
    | '/politica-de-privacidad'
    | '/quien-te-atiende'
    | '/quienes-somos'
    | '/seguros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/como-trabajamos'
    | '/contacto'
    | '/faq'
    | '/politica-de-privacidad'
    | '/quien-te-atiende'
    | '/quienes-somos'
    | '/seguros'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/como-trabajamos'
    | '/contacto'
    | '/faq'
    | '/politica-de-privacidad'
    | '/quien-te-atiende'
    | '/quienes-somos'
    | '/seguros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ComoTrabajamosRoute: typeof ComoTrabajamosRoute
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  QuienTeAtiendeRoute: typeof QuienTeAtiendeRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  SegurosRoute: typeof SegurosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabajamos': {
      id: '/como-trabajamos'
      path: '/como-trabajamos'
      fullPath: '/como-trabajamos'
      preLoaderRoute: typeof ComoTrabajamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quien-te-atiende': {
      id: '/quien-te-atiende'
      path: '/quien-te-atiende'
      fullPath: '/quien-te-atiende'
      preLoaderRoute: typeof QuienTeAtiendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ComoTrabajamosRoute: ComoTrabajamosRoute,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  QuienTeAtiendeRoute: QuienTeAtiendeRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  SegurosRoute: SegurosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
