/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuienTeAtiendeRouteImport } from './routes/quien-te-atiende'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienTeAtiendeRoute = QuienTeAtiendeRouteImport.update({
  id: '/quien-te-atiende',
  path: '/quien-te-atiende',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quien-te-atiende': typeof QuienTeAtiendeRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quien-te-atiende': typeof QuienTeAtiendeRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quien-te-atiende': typeof QuienTeAtiendeRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quien-te-atiende' | '/quienes-somos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quien-te-atiende' | '/quienes-somos'
  id: '__root__' | '/' | '/quien-te-atiende' | '/quienes-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuienTeAtiendeRoute: typeof QuienTeAtiendeRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quien-te-atiende': {
      id: '/quien-te-atiende'
      path: '/quien-te-atiende'
      fullPath: '/quien-te-atiende'
      preLoaderRoute: typeof QuienTeAtiendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuienTeAtiendeRoute: QuienTeAtiendeRoute,
  QuienesSomosRoute: QuienesSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
